# -*- coding: utf-8 -*-

import importlib
import importlib.util
import os
import setuptools

"""This file is used to package the FixLink plugin.

- It was generated by the InvenTree Plugin Creator tool - version 1.2.0
- Ref: https://github.com/inventree/plugin_creator
"""

"""Read the plugin version from the source code."""
module_path = os.path.join(os.path.dirname(__file__), "fixlink", "__init__.py")
spec = importlib.util.spec_from_file_location("fixlink", module_path)
fixlink = importlib.util.module_from_spec(spec)
spec.loader.exec_module(fixlink)

with open('README.md', encoding='utf-8') as f:
    long_description = f.read()

setuptools.setup(
    name="fixlink",
    version=fixlink.PLUGIN_VERSION,
    author="Jan Schüler",
    author_email="jandeluxe96@gmail.com",
    description="A short description of the project",
    long_description=long_description,
    long_description_content_type='text/markdown',
    url="https://inventur.asta-hsh.de",
    license="MIT",
    packages=setuptools.find_packages(),
    include_package_data=True,
    install_requires=[
        # Enter your plugin library dependencies here
    ],
    setup_requires=[
        "wheel",
        "twine",
    ],
    python_requires=">=3.9",
    entry_points={
        "inventree_plugins": [
            "FixLink = fixlink.core:FixLink"
        ]
    },
)
